# Generated by Django 6.0.4 on 2026-04-28 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_name', models.CharField(max_length=255)),
                ('activity_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('bakery', 'Bakery'), ('hotel', 'Hotel'), ('other', 'Other')], max_length=50)),
                ('commercial_registration_number', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('person_in_charge_full_name', models.CharField(max_length=255)),
                ('person_in_charge_phone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_license_number', models.CharField(max_length=100, unique=True)),
                ('target_category', models.CharField(max_length=255)),
                ('geographical_location', models.CharField(max_length=255)),
                ('person_in_charge_full_name', models.CharField(max_length=255)),
                ('person_in_charge_phone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('national_id_number', models.CharField(max_length=20, unique=True)),
                ('means_of_transportation', models.CharField(max_length=100)),
                ('areas_of_volunteering', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
