# Generated by Django 6.0.4 on 2026-04-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_and_login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='areas_of_volunteering',
            new_name='addresses',
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='geographical_location',
        ),
        migrations.RemoveField(
            model_name='receiver',
            name='target_category',
        ),
        migrations.AddField(
            model_name='receiver',
            name='address',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiver',
            name='entity_name',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='activity_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='means_of_transportation',
            field=models.CharField(max_length=50),
        ),
    ]
