# Generated by Django 6.0.4 on 2026-04-28 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_food', '0001_initial'),
        ('registration_and_login', '0002_rename_areas_of_volunteering_volunteer_addresses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafood',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration_and_login.provider'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extrafood',
            name='status',
            field=models.CharField(choices=[('NO_RECEIVER', 'No Receiver'), ('NO_DELIVERY', 'No Delivery'), ('WAITING_FOR_DELIVERY', 'Waiting For Delivery'), ('ON_THE_WAY_TO_RECEIVER', 'On The Way To Receiver'), ('DONE', 'Done'), ('FAILED', 'FAILED'), ('EXPIRED', 'Expired')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
