# Generated by Django 5.2.3 on 2026-04-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_food', '0002_extrafood_provider_extrafood_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafood',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='extrafood',
            name='status',
            field=models.CharField(choices=[('NO_RECEIVER', 'No Receiver'), ('NO_DELIVERY', 'No Delivery'), ('WAITING_FOR_DELIVERY', 'Waiting For Delivery'), ('ON_THE_WAY_TO_RECEIVER', 'On The Way To Receiver'), ('DONE', 'Done'), ('FAILED', 'FAILED'), ('EXPIRED', 'Expired')], default='NO_RECEIVER', max_length=50),
        ),
    ]
